name = "dd-mod-sorter"
type = "javascript"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "dd-mod-sorter.pages.dev", zone_name = "pages.dev" }
]

[build]
command = "npm run build"
cwd = "./"
